# Generated by Django 2.0.2 on 2019-01-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='health',
            old_name='content',
            new_name='exercise',
        ),
        migrations.AddField(
            model_name='health',
            name='accident',
            field=models.CharField(default=' ', max_length=5),
        ),
        migrations.AddField(
            model_name='health',
            name='gender',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='pain',
            field=models.CharField(default=' ', max_length=5),
        ),
        migrations.AddField(
            model_name='health',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='BMI',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='body_fat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='muscle_mass',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='smoking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
