# Generated by Django 2.0.2 on 2019-01-07 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form', '0003_auto_20190104_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='health',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='health',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='health',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='health',
            name='user',
        ),
        migrations.AddField(
            model_name='health',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='suggested_exercise',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='health',
            name='reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
