# Generated by Django 2.0.2 on 2019-01-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20190107_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='smoking',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
