# Generated by Django 2.0.2 on 2019-01-08 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_auto_20190108_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health',
            name='username',
        ),
    ]
