# Generated by Django 2.0.2 on 2019-01-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_health_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='gender',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
